# Ansible role to execute a script
---
- name: Shell scripts section
  set_fact:
    section: "{{ hostvars['localhost'].profile_json['Shell'] }}"

- shell:
    cmd: |
      "{{ item.Script }}"
  with_items: "{{ section }}"

