Commands:
- Name: env var
  Command: [ export, NONINTERACTIVE=1 ]
  Become: yes
  Become_User: max
  Become_Method: sudo
- Name: install brew
  Command: [ /bin/bash, -c, "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"]
  Become: yes
  Become_User: max
  Become_Method: sudo