Commands:
- Name: 1
  Command: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh >> /tmp/install.sh
Scripts:
- name: Copy a script from the host and execute it on the remote
  Script: "/tmp/install.sh"
  Become: yes
  Become_User: max
  Become_Method: sudo

  Command: install.sh