---
# WiP role to add aliases 
- name: Path section
  set_fact:
    section: "{{ hostvars['localhost'].profile_json['Path'] }}"
    ansible_user: "{{ hostvars['localhost'].ansible_user }}"

- name: add a new path
  ansible.builtin.lineinfile: >
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["])((?!.?{{extra_path}}).?)(["])$'
    line: "PATH=\1\2:{{ item.Path }}\3"
    create: yes
  with_items: "{{ section }}"
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: sudo
