name: Do Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: 'v0.0.0'
jobs:
  build-and-boot:
    runs-on: ubuntu-latest
    container: 
      image: deserializeme/pxeless:latest
      options: -v ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v3
      - name: Build Iso
        run: |
          /app/image-create.sh -a -k -u /data/user-data.basic -n jammy

      - name: version
        run: echo "::set-output name=version::${{ github.ref_name }}"
        id: version
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: |
            ubuntu-autoinstall.iso
          
          
