name: Create Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    container: deserializeme/pxeless:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: test
        run: |
          ./image-create.sh -a -u user-data.example -n jammy -k
