name: Build Image Iso
on:
  push:
    branches: [ "develop" ]
    tags:
      - "v*.*.*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    container: 
      image: deserializeme/pxeless:latest
      options: -v ${{ github.workspace }}:/data
    steps:
      - name: Build Iso
        run: ls -hal 
          
      - name: version
        run: echo "::set-output name=version::${{ github.ref_name }}"
        id: version
    
      - name: release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload linux artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ubuntu-autoinstall.iso
