name: Build Image Iso
on:
  push:
    branches: [ "develop" ]
    tags:
      - "v*.*.*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    container: 
      image: deserializeme/pxeless:latest
      options: -v ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v3
      - name: Build Iso
        run: |
          /app/image-create.sh -a -k -u /data/user-data.basic -n jammy
          
      - name: version
        run: echo "::set-output name=version::${{ github.ref_name }}"
        id: version
    
      - name: release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload linux artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ubuntu-autoinstall.iso
          
      - name: install qemu deps
        run: |
          apt-get update && apt-get install -y qemu-kvm \
          bridge-utils \
          virtinst\
          ovmf \
          qemu-utils \
          cloud-image-utils \
          ubuntu-drivers-common \
          whois \
          git \
          git-extras \
          guestfs-tools
          
      - uses: actions/download-artifact@main
        with:
          name: ubuntu-autoinstall.iso
          
      - name: run vm
        run: |
          qemu-img create -f qcow2 hdd.img 8G && \
          qemu-system-x86_64 \
          -machine accel=kvm,type=q35 \
          -cpu host,kvm=off,hv_vendor_id=null \
          -smp 1,sockets=1,cores=1,threads=1,maxcpus=1 \
          -m 1G \
          -cdrom ubuntu-autoinstall.iso \
          -object iothread,id=io1 \
          -device virtio-blk-pci,drive=disk0,iothread=io1 \
          -drive if=none,id=disk0,cache=none,format=qcow2,aio=threads,file=hdd.img \
          -netdev user,id=network0,hostfwd=tcp::1234-:22 \
          -device virtio-net-pci,netdev=network0 \
          -serial stdio -vga virtio -parallel none \
          -bios /usr/share/ovmf/OVMF.fd \
          -usbdevice tablet
          
