name: Do Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: 'v0.0.0'

jobs:
  generate-code-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip artifact for deployment
        run: zip pxeless-$RELEASE_VERSION.zip ./* -r
        shell: bash
        env: 
          RELEASE_VERSION: ${{github.event.inputs.release_version}}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          name: ${{github.event.inputs.release_version}}
          files: |
            pxeless-*.zip
