name: Do Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: 'v0.0.0'
jobs:
  build-and-boot:
    runs-on: ubuntu-latest
    container: 
      image: deserializeme/pxeless:latest
      options: -v ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v3

      - name: Zip Source Code Folder
        run: |
          git tag ${{ github.event.inputs.release_version }}
          tar -zcvf pxeless-$RELEASE_VERSION.tar.gz .
        shell: bash
        env:
          RELEASE_VERSION: ${{github.event.inputs.release_version}}

      #- name: Build ISO Image
      #  run: |
      #    /app/image-create.sh -a -k -u /data/user-data.basic -n jammy
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: |
            pxeless-*.zip
            #ubuntu-autoinstall.iso
          
          
