name: build docker image

on:
  push:
    branches:
      - develop
    tags:
      - "*.*.*"
  release:
    types: [created]
    tags:
      - "*.*.*"
    
jobs:
  build-basic:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag deserializeme/pxeless:latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: GitHub Tag Name example
        run: |
          echo "Tag from GITHUB_REF: $GITHUB_REF"
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          
      - name: Push the latest Docker image as a tagged version
        run: docker push deserializeme/pxeless:$GITHUB_REF_NAME
        
      - name: Push the latest Docker image and overwrite latest
        run: docker push deserializeme/pxeless:latest
