name: build docker image

on:
  push:
    branches: [ "develop" ]
    tags:
      - "v*.*.*"
    
jobs:
  build-basic:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag deserializeme/pxeless:latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push the latest Docker image
        run: docker push deserializeme/pxeless:latest
